apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: frontend-app
  ports:
    - port: 80          # সার্ভিসের ইন্টারনাল পোর্ট
      targetPort: 80    # পডের ভেতরে অ্যাপ যে পোর্টে চলছে (Nginx এর জন্য ৮০)
      nodePort: 30005   # এই পোর্টে আপনি ব্রাউজার থেকে অ্যাপ দেখবেন (Range: 30000-32767)
