apiVersion: apps/v1     # <--- Ei line-ta missing thakte pare
kind: ReplicaSet        # <--- Ei line-ta missing thakte pare
metadata:
  name: frontend-rs
  labels:
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: php-redis
        image: nginx:latest  # <--- Nginx dile ebar 100% cholbe
