apiVersion: v1
kind: Pod
metadata:
  name: pending-app
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: disktype
            operator: In
            values:
            - gpu # আমাদের কোনো নোডে gpu লেবেল নেই
  containers:
  - name: nginx
    image: nginx
