apiVersion: v1
kind: Pod
metadata:
  name: soft-app
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 1  # গুরুত্ব (১ থেকে ১০০ পর্যন্ত হতে পারে)
        preference:
          matchExpressions:
          - key: disktype
            operator: In
            values:
            - gpu  # মনে করুন আমরা GPU খুঁজছি, কিন্তু সেটা আমাদের নেই
  containers:
  - name: nginx
    image: nginx
